apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 440744220626.dkr.ecr.ap-northeast-2.amazonaws.com/nginx-image
  newName: 440744220626.dkr.ecr.ap-northeast-2.amazonaws.com/nginx-image
  newTag: 6b4628d6
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
